name: Setup
description: Setup Python & Poetry

inputs:
  python-version:
    description: The Python version to install
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python (${{ inputs.python-version }})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      uses: actions/cache@v4
      with:
        path: ~/.cache
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}
