name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency: pypi
    environment:
      name: pypi
      url: https://pypi.org/project/{{ cookiecutter.package_name }}/
{%- raw %}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.12'

      - name: Release
        uses: corentin-regent/poetrel@v1
        with:
          changelog: CHANGELOG.rst
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          setup-poetry: false
{%- endraw %}
{%- if cookiecutter.docs %}
{%- raw %}

  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    needs: release
    permissions:
      pages: write
      id-token: write
    concurrency: github-pages
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: poetry install --no-interaction --with docs

      - name: Build docs
        run: poetry run sphinx-build ./docs ./docs/_build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
{%- endraw %}
{%- endif %}
